spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/home_smart_factory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: false
  main:
    web-application-type: none
